# Generated by Django 5.2 on 2025-04-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('team_leader', 'Team Leader'), ('company', 'Company')], default='applicant', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
